---

cluster_path: "{{ ansible_facts['user_dir'] }}/pgedge"
pg_path: "{{ cluster_path }}/pg{{ pg_version }}"
pg_data: "{{ cluster_path }}/data/pg{{ pg_version }}"

zone_list: >
    {{ groups['all'] |
    map('extract', hostvars) |
    map(attribute='zone') | unique | list }}

nodes_in_zone: >
    {{ groups['pgedge'] |
    map('extract', hostvars) |
    selectattr('zone', 'eq', zone) |
    map(attribute='inventory_hostname') | list }}

proxies_in_zone: >
    {{ groups['haproxy'] |
    map('extract', hostvars) |
    selectattr('zone', 'eq', zone) |
    map(attribute='inventory_hostname') | list }}

first_node_in_zone: "{{ nodes_in_zone | first }}"
first_proxy_in_zone: "{{ proxies_in_zone | first }}"

# This variable is supplied in the event of hybrid clusters where some pgEdge
# nodes have HA replicas and a proxy set up, and others don't.

subscribe_target: "{{ first_proxy_in_zone | default(first_node_in_zone) }}"
