---

zone_list: >
    {{ groups['all'] |
    map('extract', hostvars) |
    map(attribute='zone') | unique | list }}

proxies_in_zone: >
    {{ groups['haproxy'] |
    map('extract', hostvars) |
    selectattr('zone', 'eq', zone) |
    map(attribute='inventory_hostname') | list }}

first_proxy_in_zone: "{{ proxies_in_zone | first }}"

# This variable is supplied in the event of hybrid clusters where some pgEdge
# nodes have HA replicas and a proxy set up, and others don't.

subscribe_target: "{{ first_proxy_in_zone | default(first_node_in_zone) }}"
