---

- name: Check for etcd data directory for this cluster
  stat:
    path: "{{ etcd_data_dir }}/postgresql"
  register: etcd_data
  become: true

- include_tasks: setup.yaml
  when: not etcd_data.stat.exists
