# This playbook will create an HA cluster assuming three node groups:
#
# * pgedge - will receive etcd, Patroni, and pgEdge
# * haproxy - will receive haproxy
# * backup - will act as a dedicated backup server per zone
#
# CHECK the README for how these roles work
---

# All hosts being managed by this collection should be initialized. This will
# set up SSH host keys in some cases and other prerequisites which may be
# used by followup roles

- hosts: all
  any_errors_fatal: true

  collections:
  - pgedge.platform

  roles:
  - init_server

# Begin deployment by "bootstrapping" all pgedge nodes with running software:
#
# - Postgres
# - etcd
# - Patroni
#
# This will also install and configure any pgEdge Distributed Postgres
# extensions necessary for the cluster to operate.

- hosts: pgedge
  any_errors_fatal: true

  collections:
  - pgedge.platform

  roles:
  - install_pgedge
  - setup_postgres
  - install_etcd
  - install_patroni
  - install_backrest
  - setup_etcd
  - setup_patroni
  - setup_backrest

# Install HAProxy on dedicated proxy nodes.
#
# Do this here to ensure Patroni is up and running and providing a REST
# interface for HAProxy to use for validating endpoints.

- hosts: haproxy

  collections:
  - pgedge.platform

  roles:
  - setup_haproxy

# Then "wire" the pgEdge cluster members together using Ultra-HA design

- hosts: pgedge

  collections:
  - pgedge.platform

  roles:
  - setup_pgedge

# Finally, set up the backup server so we capture the final state of any
# working primary nodes post-deployment.

- hosts: backup

  collections:
  - pgedge.platform

  roles:
  - install_pgedge
  - install_backrest
  - setup_backrest
