# This playbook will create an HA cluster assuming two node groups:
#
# * pgedge - will receive etcd, Patroni, and pgEdge
# * haproxy - will receive haproxy
#
# CHECK the README for how these roles work
---

- hosts: pgedge
  roles:
  - init_server
  - install_pgedge
  - setup_postgres
  - install_etcd
  - install_patroni
  - setup_etcd
  - setup_patroni

- hosts: haproxy
  roles:
  - init_server
  - setup_haproxy

- hosts: pgedge
  roles:
  - setup_pgedge
