# This playbook will create a standard pgEdge cluster
#
# Make sure all nodes are in the pgedge node group.
#
# CHECK the README for how these roles work
---

- hosts: pgedge
  roles:
  - init_server
  - install_pgedge
  - setup_postgres
  - install_etcd
  - install_patroni
  - setup_etcd
  - setup_patroni
  - setup_pgedge
