---

- name: Include Packages Patroni needs to run or operate
  package:
    name:
    - python3-psycopg2
    - python3-pip
    state: present
  become: true

- name: Install Python prerequisites with pip
  shell: |
    pip3 install -r /usr/local/patroni/requirements.txt
    pip3 install cdiff
