---

- name: Create .bashrc.d environment directory if missing
  file:
    path: "{{ ansible_user_dir }}/.bashrc.d"
    state: directory

- name: Make sure to source .bashrc.d files on login
  blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    insertbefore: BOF
    state: present
    marker: "# {mark} pgEdge ANSIBLE MANAGED BLOCK"
    block: |
      for env_file in ~/.bashrc.d/*.sh; do
        . ${env_file}
      done
