---

cluster_path: "{{ ansible_facts['user_dir'] }}/pgedge"

nodes_in_zone: |
    {{ groups['pgedge'] |
    map('extract', hostvars) |
    selectattr('zone', 'eq', zone) |
    map(attribute='inventory_hostname') }}
