---

- name: Include psycopg2 for Postgres administration uses
  package:
    name:
    - python3-psycopg2
    state: present
    lock_timeout: 300
  retries: 5
  delay: 20
  register: result
  until: result is success
  become: true
