---

# Install pgBouncer from the pgEdge repo. Configuration is handled separately
# by the setup_pgbouncer role.

- name: Ensure pgBouncer is installed
  package:
    name: "{{ pgbouncer_package }}"
    state: present
    lock_timeout: 300
    update_cache: true
  retries: 5
  delay: 20
  register: result
  until: result is success
  become: true
