---

- name: Add etcd utilities to the user path
  lineinfile:
    path: "{{ ansible_facts['user_dir'] }}/.bashrc.d/etcd_env.sh"
    line: "export PATH=${PATH}:{{ etcd_install_dir }}"
    create: true
