---

- name: Check for etcd software
  stat:
    path: "/usr/local/etcd"
  register: etcd_software

- include_tasks: install.yaml
  when: not etcd_software.stat.exists

- include_tasks: environment.yaml
