---

- name: Check for etcd binary
  stat:
    path: "{{ etcd_install_dir }}/etcd"
  register: etcd_binary

- include_tasks: install.yaml
  when: not etcd_binary.stat.exists

- include_tasks: environment.yaml
