# This inventory will produce a pgEdge cluster with the following:
#
# * 3 zones
# * 1 pgEdge node in each zone
#
# Note: zones are currently a logical node assignment. This is also
#       used for snowflake IDs.

pgedge:
  vars:
    db_password: secret
  hosts:
    192.168.6.10:
      zone: 1
    192.168.6.11:
      zone: 2
    192.168.6.12:
      zone: 3
