# This playbook will create a standard pgEdge cluster
#
# Make sure all nodes are in the pgedge node group.
#
# Set pgbouncer_enabled on that group to give every node a connection pooler in
# front of its own Postgres.
#
# CHECK the README for how these roles work
---

- hosts: pgedge

  collections:
  - pgedge.platform

  roles:
  - init_server
  - install_repos
  - install_pgedge
  - role: install_pgbouncer
    when: pgbouncer_enabled | bool
  - setup_postgres
  - role: setup_pgbouncer
    when: pgbouncer_enabled | bool
  - setup_pgedge
