# This playbook will create a standard pgEdge cluster
#
# Make sure all nodes are in the pgedge node group.
#
# CHECK the README for how these roles work
---

- hosts: pgedge

  collections:
  - pgedge.platform

  roles:
  - init_server
  - install_pgedge
  - setup_postgres
  - setup_pgedge
