# This playbook will create a standard pgEdge cluster
#
# Make sure all nodes are in the pgedge node group.
#
# Nodes that should also run a connection pooler go in the optional pgbouncer
# group, which must be a subset of pgedge.
#
# CHECK the README for how these roles work
---

- hosts: pgedge

  collections:
  - pgedge.platform

  roles:
  - init_server
  - install_repos
  - install_pgedge
  - role: install_pgbouncer
    when: inventory_hostname in (groups['pgbouncer'] | default([]))
  - setup_postgres
  - role: setup_pgbouncer
    when: inventory_hostname in (groups['pgbouncer'] | default([]))
  - setup_pgedge
