---

- name: Include Packages HAProxy needs to run or operate
  package:
    name:
    - haproxy
    state: present
    lock_timeout: 300
  retries: 5
  delay: 20
  register: result
  until: result is success
  become: true
