---

- name: Add pgEdge utilities to the user path
  lineinfile:
    path: "{{ ansible_facts['user_dir'] }}/.bashrc.d/pgedge_env.sh"
    line: "export PATH=${PATH}:{{ cluster_path }}"
    create: true
